// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo2fWbaJgDGwLI3BavWdxGoh0hLfitre8',
    appId: '1:54649021565:web:f76b53148b8ff47aabfd14',
    messagingSenderId: '54649021565',
    projectId: 'chat-gpt-2-5087d',
    authDomain: 'chat-gpt-2-5087d.firebaseapp.com',
    storageBucket: 'chat-gpt-2-5087d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5tVzKG6quBPHGZMhCfWf_hza4gjFeYH4',
    appId: '1:54649021565:android:ae099e42d197530aabfd14',
    messagingSenderId: '54649021565',
    projectId: 'chat-gpt-2-5087d',
    storageBucket: 'chat-gpt-2-5087d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0G3-aA7B4uGR1OgNqPJB_1U8CaZBBzq8',
    appId: '1:54649021565:ios:5fcf7dfe0dc14bf3abfd14',
    messagingSenderId: '54649021565',
    projectId: 'chat-gpt-2-5087d',
    storageBucket: 'chat-gpt-2-5087d.appspot.com',
    iosClientId: '54649021565-5ja8tpvvabrgnjmbovoejvmd649jn5gp.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatGpt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0G3-aA7B4uGR1OgNqPJB_1U8CaZBBzq8',
    appId: '1:54649021565:ios:74bde9df27bdcee5abfd14',
    messagingSenderId: '54649021565',
    projectId: 'chat-gpt-2-5087d',
    storageBucket: 'chat-gpt-2-5087d.appspot.com',
    iosClientId: '54649021565-5ok6vnm97a19frccsp08nss9th8gaphu.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatGpt.RunnerTests',
  );
}
