// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCbMw2uaDeNjiYygMND2pbTLfAyDXzdDw',
    appId: '1:515052592241:web:d752229fd78f8b80c64fd0',
    messagingSenderId: '515052592241',
    projectId: 'appal-fyp',
    authDomain: 'appal-fyp.firebaseapp.com',
    storageBucket: 'appal-fyp.appspot.com',
    measurementId: 'G-74WEHNZ4EV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0JSZhCokpClNHSOgFrjQrxSnQmyW5_V4',
    appId: '1:515052592241:android:dd6f6acf65252606c64fd0',
    messagingSenderId: '515052592241',
    projectId: 'appal-fyp',
    storageBucket: 'appal-fyp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsGUC-I6ulCgMHBIghNnh7EBy9w_DYswc',
    appId: '1:515052592241:ios:c331987f556db3a9c64fd0',
    messagingSenderId: '515052592241',
    projectId: 'appal-fyp',
    storageBucket: 'appal-fyp.appspot.com',
    androidClientId: '515052592241-5ls824k1h7o0rin1dhqkj0u2t719kph2.apps.googleusercontent.com',
    iosClientId: '515052592241-t0d13edlrals447k7elr45mtrcbkt13l.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatGpt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsGUC-I6ulCgMHBIghNnh7EBy9w_DYswc',
    appId: '1:515052592241:ios:e76d5e37acd2e926c64fd0',
    messagingSenderId: '515052592241',
    projectId: 'appal-fyp',
    storageBucket: 'appal-fyp.appspot.com',
    androidClientId: '515052592241-5ls824k1h7o0rin1dhqkj0u2t719kph2.apps.googleusercontent.com',
    iosClientId: '515052592241-7bgpccbs93q1fp2g4161k079hme5dq4c.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatGpt.RunnerTests',
  );
}
